# Generated by Django 3.2.22 on 2024-01-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrition',
            new_name='description',
        ),
    ]
